# Generated by Django 4.0.6 on 2022-11-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='store_cat',
        ),
        migrations.DeleteModel(
            name='StoreCategoryModel',
        ),
    ]
