# Generated by Django 4.0.6 on 2022-11-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productmodel_like'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.productmodel', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='likes_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
