# Generated by Django 4.0.6 on 2022-11-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_commentsmodel_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='likes_number',
        ),
    ]
