# Generated by Django 4.0.6 on 2022-11-29 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_likemodel_likes_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateMoled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیاز ها',
            },
        ),
        migrations.RemoveField(
            model_name='commentsmodel',
            name='rank',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='history.ratemoled', verbose_name='مقدار دهی'),
            preserve_default=False,
        ),
    ]
