# Generated by Django 4.0.6 on 2022-11-29 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_productmodel_rate'),
        ('history', '0004_ratemoled_remove_commentsmodel_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='rate',
        ),
        migrations.AddField(
            model_name='ratemoled',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productmodel', verbose_name='محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratemoled',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
