# Generated by Django 4.0.6 on 2022-11-29 11:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_productmodel_rate'),
        ('history', '0005_remove_commentsmodel_rate_ratemoled_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RateMoled',
            new_name='RateModel',
        ),
    ]
