# Generated by Django 4.0.6 on 2022-11-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_rename_ratemoled_ratemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likemodel',
            old_name='favorite_product',
            new_name='product',
        ),
    ]
