# Generated by Django 4.0.6 on 2022-11-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_rename_favorite_product_likemodel_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
