# Generated by Django 4.0.6 on 2022-12-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_delete_likemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritemodel',
            old_name='favorite_product',
            new_name='product',
        ),
    ]
