# Generated by Django 4.0.6 on 2022-12-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_rename_favorite_product_favoritemodel_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseItems',
        ),
    ]
