# Generated by Django 4.0.6 on 2022-12-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productmodel_is_fave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_cart_item_discount_order_datails_order_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ایتم سبد',
                'verbose_name_plural': 'ایتم های سبد',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید',
            },
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='session',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='order_datails',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order_datails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment_details',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment_details',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='shopping_session',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart_Item',
        ),
        migrations.DeleteModel(
            name='Order_Datails',
        ),
        migrations.DeleteModel(
            name='Order_Items',
        ),
        migrations.DeleteModel(
            name='Payment_Details',
        ),
        migrations.DeleteModel(
            name='Shopping_Session',
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartmodel'),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='product',
            field=models.ManyToManyField(to='product.productmodel'),
        ),
    ]
