# Generated by Django 4.0.6 on 2022-12-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitemmodel_cartmodel_remove_cart_item_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitemmodel',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
