# Generated by Django 4.0.6 on 2022-12-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_price_cartitemmodel_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='total_price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
