# Generated by Django 4.0.6 on 2022-12-10 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartitemmodel_cart_alter_cartitemmodel_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='تخفیف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات تخفیف')),
                ('deiscount_percent', models.FloatField(verbose_name='رقم تخفیف')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شد'),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.discountmodel', verbose_name='تخفیف کلی'),
        ),
    ]
