# Generated by Django 4.0.6 on 2023-01-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_cart_item_model_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item_model',
            name='increment_count',
            field=models.BooleanField(default=False, verbose_name='موجود بودن در سبد'),
        ),
    ]
