# Generated by Django 4.0.6 on 2022-11-24 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برند محصول',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': ' دسته محصول',
                'verbose_name_plural': 'دسته محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس محصول',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categorymodel')),
            ],
            options={
                'verbose_name': ' زیر دسته محصول',
                'verbose_name_plural': 'زیر دسته محصولات',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' تگ',
                'verbose_name_plural': ' تگ ها',
            },
        ),
        migrations.CreateModel(
            name='SubSubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('SubCategoryModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategorymodel')),
            ],
            options={
                'verbose_name': 'زیر زیر دسته محصول',
                'verbose_name_plural': 'زیر زیر دسته محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='اسم محصول')),
                ('weight', models.CharField(blank=True, max_length=40, null=True, verbose_name='وزن')),
                ('size', models.CharField(blank=True, max_length=40, null=True, verbose_name='ابعاد')),
                ('cpu_creator', models.CharField(choices=[('intel', 'intel'), ('ryzen', 'ryzen')], default='intel', max_length=40, verbose_name='سازنده پردازنده')),
                ('cpu_series', models.CharField(max_length=40, verbose_name='سری پردازنده')),
                ('cpu_model', models.CharField(blank=True, max_length=40, null=True, verbose_name='مدل پردازنده')),
                ('cpu_speed_range', models.CharField(blank=True, max_length=40, null=True, verbose_name='محدوده سرعت پردازنده')),
                ('processor_frequency', models.CharField(blank=True, max_length=40, null=True, verbose_name='فرکانس پردازنده')),
                ('cache_memory', models.CharField(blank=True, max_length=40, null=True, verbose_name='حافظه Cache')),
                ('extra_cpu_des', models.CharField(blank=True, max_length=40, null=True, verbose_name='سایر توضیحات پردازنده مرکزی (CPU)')),
                ('ram', models.CharField(max_length=40, verbose_name='ظرفیت حافظه RAM')),
                ('ram_type', models.CharField(choices=[('ddr3', 'ddr3'), ('ddr4', 'ddr4'), ('ddr5', 'ddr5')], default='ddr4', max_length=6, verbose_name='نوع حافظه RAM')),
                ('extra_ram_des', models.CharField(blank=True, max_length=40, null=True, verbose_name='سایر توضیحات حافظه RAM')),
                ('internal_memory_capacity', models.CharField(max_length=40, verbose_name='ظرفیت حافظه داخلی')),
                ('internal_memory_type', models.CharField(choices=[('ssd', 'ssd'), ('hdd', 'hdd')], default='ssd', max_length=40, verbose_name='نوع حافظه داخلی')),
                ('extra_internal_memory_des', models.CharField(blank=True, max_length=40, null=True, verbose_name='سایر توضیحات حافظه داخلی')),
                ('gpu_manufacturer', models.CharField(max_length=40, verbose_name='سازنده پردازنده گرافیکی')),
                ('gpu_model', models.CharField(max_length=40, verbose_name='مدل پردازنده گرافیکی')),
                ('gpu_memory', models.CharField(max_length=40, verbose_name='حافظه اختصاصی پردازنده گرافیکی')),
                ('screen_size', models.CharField(choices=[('11.6', '11.6'), ('12.5', '12.5'), ('13.3', '13.3'), ('14', '14'), ('15.6', '15.6'), ('16.1', '16.1'), ('17', '17')], default='15.6', max_length=40, verbose_name='اندازه صفحه نمایش')),
                ('screen_resolution', models.CharField(max_length=40, verbose_name='دقت صفحه نمایش')),
                ('screen_resolution_des', models.CharField(blank=True, max_length=40, null=True, verbose_name='توضیحات صفحه نمایش')),
                ('device_capabilities', models.CharField(blank=True, max_length=40, null=True, verbose_name='قابلیت\u200cهای دستگاه')),
                ('optical_drive', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=40, verbose_name='درایو نوری')),
                ('speaker_description', models.CharField(blank=True, max_length=40, null=True, verbose_name='مشخصات اسپیکر')),
                ('ports', models.CharField(blank=True, max_length=2, null=True, verbose_name='درگاه\u200cهای ارتباطی')),
                ('usb_2_ports', models.CharField(blank=True, max_length=2, null=True, verbose_name='تعداد پورت USB 2.0')),
                ('usb_3_ports', models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد پورت USB 3.2')),
                ('classification', models.CharField(choices=[('multimedia', 'multimedia'), ('gaming', 'gaming')], default='multimedia', max_length=40, verbose_name='طبقه\u200cبندی')),
                ('battery_type', models.CharField(max_length=40, verbose_name='نوع باتری')),
                ('battery_description', models.CharField(blank=True, max_length=40, null=True, verbose_name='توضیحات باتری')),
                ('operating_system', models.CharField(choices=[('windows', 'windows'), ('linux', 'linux'), ('mac', 'mac')], default='windows', max_length=40, verbose_name='سیستم عامل')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد محصول')),
                ('condition', models.CharField(choices=[('stock', 'stock'), ('openbox', 'openbox'), ('new', 'new')], default='stock', max_length=20, verbose_name='وضعیت لب تاب')),
                ('offer', models.IntegerField(default=0, null=True, verbose_name='تخفیف محصول ')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brandmodel', verbose_name='برند محصول')),
                ('product_image', models.ManyToManyField(to='product.productimage')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storemodel')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategorymodel', verbose_name=' زیر دسته محصول')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tagmodel', verbose_name='تگ محصول')),
            ],
            options={
                'verbose_name': ' محصول',
                'verbose_name_plural': ' محصولات',
            },
        ),
    ]
