# Generated by Django 4.0.6 on 2022-11-25 09:26

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to=product.models.Profile_image_path, verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
