# Generated by Django 4.0.6 on 2022-11-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='screen_size',
            field=models.CharField(choices=[('11.6', '11.6'), ('12.5', '12.5'), ('13.3', '13.3'), ('14', '14'), ('15.6', '15.6'), ('16.1', '16.1'), ('17', '17')], default='17', max_length=40, verbose_name='اندازه صفحه نمایش'),
        ),
    ]
