# Generated by Django 4.0.6 on 2022-11-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productmodel_screen_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='classification',
            field=models.CharField(max_length=40, verbose_name='طبقه\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='condition',
            field=models.CharField(max_length=20, verbose_name='وضعیت لب تاب'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='cpu_creator',
            field=models.CharField(max_length=40, verbose_name='سازنده پردازنده'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='internal_memory_type',
            field=models.CharField(max_length=40, verbose_name='نوع حافظه داخلی'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='operating_system',
            field=models.CharField(max_length=40, verbose_name='سیستم عامل'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='optical_drive',
            field=models.CharField(max_length=40, verbose_name='درایو نوری'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='ram_type',
            field=models.CharField(max_length=6, verbose_name='نوع حافظه RAM'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='screen_size',
            field=models.CharField(max_length=40, verbose_name='اندازه صفحه نمایش'),
        ),
    ]
