# Generated by Django 4.0.6 on 2022-11-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productmodel_battery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='battery_description',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='توضیحات باتری'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='battery_type',
            field=models.CharField(default=1, max_length=40, verbose_name='نوع باتری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cache_memory',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='حافظه Cache'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='classification',
            field=models.CharField(default=1, max_length=40, verbose_name='طبقه\u200cبندی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='condition',
            field=models.CharField(default=1, max_length=20, verbose_name='وضعیت لب تاب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cpu_creator',
            field=models.CharField(default=1, max_length=40, verbose_name='سازنده پردازنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='مدل پردازنده'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cpu_series',
            field=models.CharField(default=1, max_length=40, verbose_name='سری پردازنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cpu_speed_range',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='محدوده سرعت پردازنده'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='device_capabilities',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='قابلیت\u200cهای دستگاه'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='extra_cpu_des',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='سایر توضیحات پردازنده مرکزی (CPU)'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='extra_internal_memory_des',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='سایر توضیحات حافظه داخلی'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='extra_ram_des',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='سایر توضیحات حافظه RAM'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='gpu_manufacturer',
            field=models.CharField(default=1, max_length=40, verbose_name='سازنده پردازنده گرافیکی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='gpu_memory',
            field=models.CharField(default=1, max_length=40, verbose_name='حافظه اختصاصی پردازنده گرافیکی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='gpu_model',
            field=models.CharField(default=1, max_length=40, verbose_name='مدل پردازنده گرافیکی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='internal_memory_capacity',
            field=models.CharField(default=1, max_length=40, verbose_name='ظرفیت حافظه داخلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='internal_memory_type',
            field=models.CharField(default=1, max_length=40, verbose_name='نوع حافظه داخلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='operating_system',
            field=models.CharField(default=1, max_length=40, verbose_name='سیستم عامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='optical_drive',
            field=models.CharField(default=1, max_length=40, verbose_name='درایو نوری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='ports',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='درگاه\u200cهای ارتباطی'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='processor_frequency',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='فرکانس پردازنده'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='ram',
            field=models.CharField(default=1, max_length=40, verbose_name='ظرفیت حافظه RAM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='ram_type',
            field=models.CharField(default=1, max_length=6, verbose_name='نوع حافظه RAM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='screen_resolution',
            field=models.CharField(default=1, max_length=40, verbose_name='دقت صفحه نمایش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='screen_resolution_des',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='توضیحات صفحه نمایش'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='screen_size',
            field=models.CharField(default=1, max_length=40, verbose_name='اندازه صفحه نمایش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ابعاد'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='speaker_description',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='مشخصات اسپیکر'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='usb_2_ports',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='تعداد پورت USB 2.0'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='usb_3_ports',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد پورت USB 3.2'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='weight',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='وزن'),
        ),
    ]
