# Generated by Django 4.0.6 on 2022-11-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productmodel_battery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name='لایک ها'),
        ),
    ]
