# Generated by Django 4.0.6 on 2022-11-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productmodel_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='like',
            new_name='likes',
        ),
    ]
