# Generated by Django 4.0.6 on 2022-11-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_like_productmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='rate',
            field=models.IntegerField(blank=True, default=0, verbose_name='امتیاز'),
        ),
    ]
