# Generated by Django 4.0.6 on 2022-12-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productmodel_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='likes',
        ),
    ]
