# Generated by Django 4.0.6 on 2022-12-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_productmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_fave',
            field=models.BooleanField(default=False),
        ),
    ]
