# Generated by Django 4.0.6 on 2023-01-28 07:21

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productmodel_is_fave'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU_CHOICES_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_creator', models.CharField(max_length=50, verbose_name='سازنده پردازنده')),
            ],
            options={
                'verbose_name': 'مدل پردازنده',
                'verbose_name_plural': 'مدل پردازنده',
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to=product.models.Profile_image_path, verbose_name='عکس های اضافی'),
        ),
    ]
